name: aprende_mas
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  dio: ^5.4.3
  flutter_dotenv: ^5.1.0
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.3
  path: ^1.9.0
  file_picker: ^8.0.3
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  share_plus: ^9.0.0
  flutter_markdown: ^0.6.14
  async: ^2.11.0
  google_nav_bar: ^5.0.7
  dynamic_color: ^1.7.0
  line_icons: ^2.0.3
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0

  drift_dev: ^2.18.0

flutter:
  uses-material-design: true
  assets:
    - .env
